### ISSUE TITLE
楼主项目打包打不了

### ISSUE THREAD

**Issue by Mrshengjie** [prontera/solar#12]
原因好像就因为你那个common-dps的问题.好多东西在它里面引用完,在其它项目要重新引用!

**Comment by prontera** [comment]
`mvn clean package` 一切正常，望能提供更为详细的信息。

**Comment by Mrshengjie** [comment]
eclipse maven install (account-ms)报:
[ERROR] Failed to execute goal on project account-ms: Could not resolve dependencies for project com.github.prontera:account-ms:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [com.github.prontera:common-dps:jar:0.0.1-SNAPSHOT (compile), org.springframework.cloud:spring-cloud-starter-config:jar:1.2.3.RELEASE (compile), org.springframework.cloud:spring-cloud-starter-bus-amqp:jar:1.2.2.RELEASE (compile), org.springframework.cloud:spring-cloud-starter-eureka:jar:1.2.6.RELEASE (compile), org.springframework.cloud:spring-cloud-starter-hystrix:jar:1.2.6.RELEASE (compile), org.springframework.cloud:spring-cloud-starter-feign:jar:1.2.6.RELEASE (compile), org.springframework.boot:spring-boot-starter-actuator:jar:1.4.5.RELEASE (compile), org.springframework.boot:spring-boot-starter-amqp:jar:1.4.5.RELEASE (compile), org.springframework.boot:spring-boot-starter-test:jar:1.4.5.RELEASE (test), com.auth0:java-jwt:jar:3.1.0 (compile), org.flywaydb:flyway-core:jar:3.2.1 (compile)]: Failed to read artifact descriptor for com.github.prontera:common-dps:jar:0.0.1-SNAPSHOT: Could not find artifact com.github.prontera:spring-cloud-microservice:pom:0.0.1-SNAPSHOT in alimaven (http://maven.aliyun.com/nexus/content/groups/public/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by prontera** [comment]
` Could not find artifact com.github.prontera:spring-cloud-microservice:pom:0.0.1-SNAPSHOT in alimaven ` ，若是想在其他项目中引用，请手工解决依赖问题。

**Comment by Mrshengjie** [comment]
主要是跟你的comm那项目有关系...因为那个pom文件中没有spring boot的maven插件,加插件还不能加因为spring boot的application的主文件没有.

**Comment by prontera** [comment]
@Mrshengjie 您好，这与本仓库的使用技法与编码优化无关，如有其他问题欢迎新开issue。
