### ISSUE TITLE
hystrix-dashboard-ms Exception

### ISSUE THREAD

**Issue by jiulingchen** [prontera/solar#14]
`ERROR 951 --- [InstanceMonitor] c.n.t.monitor.instance.InstanceMonitor   : Could not initiate connection to host, giving up: [{"timestamp":1499224918284,"status":503,"error":"Service Unavailable","message":"MaxConcurrentConnections reached: 5","path":"/78d504ff-82e8-4a87-82e8-724d72d1171b/hystrix.stream"}]`

**Comment by prontera** [comment]
MaxConcurrentConnections reached 5 我以前曾经遇过，那次是因为我打开了多个hystrix.stream监控窗口导致达到了上限，而目前我经过简单地测试并不能重现这个异常，请问你是如何测出这个异常的，如果有具体的步骤那就更好了。

**Comment by jiulingchen** [comment]
有没有考虑加入授权认证模块进来呢？

**Comment by prontera** [comment]
曾经有考虑使用JWT验证，可是这样不利用直接使用Swagger调试，考虑到本项目的性质所以暂时将这个feature的开发搁置。

**Comment by prontera** [comment]
因没有更进一步的反馈故关闭该话题，如有更多的问题欢迎新开issue。
