### ISSUE TITLE
楼主你的示例图用的什么工具画的

### ISSUE THREAD

**Issue by ghost** [prontera/solar#15]
如题。

**Comment by prontera** [comment]
OmniGraffle

**Comment by prontera** [comment]
因没有更进一步的反馈故关闭该话题，如有更多的问题欢迎新开issue。

**Comment by ghost** [comment]
能不能发一个OmniGraffle的模版（如您画的架构图）。

**Comment by prontera** [comment]
https://stenciltown.omnigroup.com/stencils/hand-drawn-objects/download/

@cnicy
