### ISSUE TITLE
楼主是否可以将你的Security 服务更新上来。

### ISSUE THREAD

**Issue by jiulingchen** [prontera/solar#16]
如题

**Comment by prontera** [comment]
你好，目前鉴权功能尚未在开发计划之内。

**Comment by ghost** [comment]
同求！

**Comment by ghost** [comment]
可以参考
https://github.com/monkey-codes/spring-boot-authentication

**Comment by jiulingchen** [comment]
@cnicy 这种方式我曾尝试过，但是我还没有弄明白 @prontera 的zuul路由order、account、product、membership服务是怎么做的。

**Comment by prontera** [comment]
感谢两位对本项目的关注，若是日后决定加入鉴权模块的时候，必定先会好好阅读上述资料。

**Comment by ghost** [comment]
@jiulingchen  确实spring cloud security有些复杂，服务之间的鉴权大致是采用无状态的JWT。
可以看看这篇文章，搭建一个demo感受一下，估计就比较好理解了。
[http://www.jianshu.com/p/6307c89fe3fa](url)

**Comment by prontera** [comment]
服务间的鉴权可以使用JWT，但是必须配合HTTPS使用。实际上多数客户端HTTPS请求仅截至Nginx，然后由Nginx路由至具体的下游服务，下游服务之间仅使用HTTP进行通讯，如果加上HTTPS的话那么将会花费更多的时间在SSL握手上。JWT感觉较适用于客户端的鉴权，并且流转在各个服务之间，对于服务与服务之间的鉴权在认知上并不是太偏向于JWT。而OAuth2也是适用于提供第三方登录的鉴权功能，用于服务与服务之间的鉴权也是过于复杂。目前来说，对于下游服务之间的鉴权，个人较为偏向于使用传统的认证方式，即协商对称密钥和报文签名。@jiulingchen @cnicy 如有更好的想法可以继续探讨。

**Comment by jiulingchen** [comment]
可以参照https://github.com/gavin-guo/spring-cloud-demo.git

这个项目的鉴权方式

**Comment by prontera** [comment]
@jiulingchen 好的，感谢你们的反馈哈

**Comment by hw1995** [comment]
Do you have a QQ group? I want to join it;

**Comment by prontera** [comment]
@hw1995 目前还没有QQ群，Github issue也是一个十分棒的交流场所。

**Comment by eumji025** [comment]
oauth2的例子还是蛮多

**Comment by prontera** [comment]
项目已更新，着重叙述rest-tcc，已去掉security相关内容，请各位见谅！
