### ISSUE TITLE
com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by deyuanchen** [prontera/solar#22]
com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect

运行项目会报这个错误

**Comment by deyuanchen** [comment]
怎么解决，求指导

**Comment by prontera** [comment]
请描述该异常是如何产生的，操作步骤及其复现方式。

**Comment by summercelery** [comment]
eureka的配置文件名改成application.yml  @deyuanchen

**Comment by prontera** [comment]
因没有更进一步的反馈故关闭该话题，如有更多的问题欢迎新开issue。
