### ISSUE TITLE
rabbitmq手动确认问题

### ISSUE THREAD

**Issue by tuxin95** [prontera/solar#23]
首先感谢楼主提供很好的代码示例！但是mq那里消费者没有设置手动确认 这样一单程序处理出现异常 消息不就丢失了吗？

**Comment by prontera** [comment]
您好，感谢您对本项目的关注。RabbitMQ的手工确认由spring boot rabbitmq所托管，如果抛出异常则有可能进入死信队列，可以关注我博客上的文章 http://blog.chriscs.com/2017/03/05/spring-boot-rabbitmq-2/

**Comment by prontera** [comment]
因没有更进一步的反馈故关闭该话题，如有更多的问题欢迎新开issue。
