### ISSUE TITLE
solar_mysql docker启动不了是什么问题啊

### ISSUE THREAD

**Issue by jinxingit** [prontera/solar#25]
host已经配置了，但找不到solar_mysql的docker实例，docker logs看未见异常，rabbitmq却起来了。。。

**Comment by prontera** [comment]
你好，感谢你对本项目的关注。docker logs未见异常是好事，但是看不到docker实例是不应该的。首先需要确认的是该错误是否属于可复现类型，其次需要贴出相关的信息及其复现步骤，例如docker ps等，方便排错。

**Comment by jinxingit** [comment]
你好，问题是，我的Docker是1.17，不是 1.13.1，在下载mysql时出现了问题，降了版本就好了，谢谢解答

**Comment by prontera** [comment]
客气，如有其他问题欢迎新开Issue。
