### ISSUE TITLE
为什么一个@EnableEurekaClient注解都没有？

### ISSUE THREAD

**Issue by phuang-git** [prontera/solar#26]
问个比较弱鸡的问题。我仔细看了项目路源码。但是有个让我疑惑地方就是。所有eureka client项目都 没有添加@EnableEurekaClient注解。但是eureka服务端却能获取到。这是为什么？

**Comment by dreamtan** [comment]
@SpringCloudApplication=下面三个注解：
@SpringBootApplication
@EnableDiscoveryClient
@EnableCircuitBreaker
