### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by 0k3** [prontera/solar#28]
hi，我下载下来，导入工程，发现代码似乎有缺失。
SwaggerApiInfo为什么没有get set方法？
SwaggerConfiguration 23行 SwaggerApiInfo.builder() builder方法找不到？
大神，是不是我这边少了什么东西呢？

**Comment by prontera** [comment]
感谢您对本项目的关注，请安装lombok插件。

**Comment by 0k3** [comment]
是的，就是这个原因，之前没有用过lombok，谢谢~~~
