### ISSUE TITLE
服务启动后 业务层的几个模块自动退出

### ISSUE THREAD

**Issue by kakarotto1989** [prontera/solar#30]
您好 我使用docker-compose启动服务后，最后几个业务层的模块，好像注册不上去，而且过几分钟后，order，product，account几个容器服务，会自动关闭退出

**Comment by chinaestone** [comment]
楼上问题最后如何解决的？ @kakarotto1989  

我这边在ide里面可以正常启动。运行docker的物理主机8核 8g的mac book pro。

现在初步判断为docker容器所需内存资源不够。不过还在测试中。楼上如果已解决问题，请指教。

**Comment by kakarotto1989** [comment]
@chinaestone ，额。。。 ，sorry，我没有解决，还在研究呢~~~
