### ISSUE TITLE
镜像中的 mysql 服务启动不了 

### ISSUE THREAD

**Issue by bolyack** [prontera/solar#32]
镜像中的 mysql 服务启动不了 ， docker-compose -f infrastructure-compose.yml up -d ， 只启动了rabbitmq服务

**Comment by prontera** [comment]
感谢您对本项目的关注，请列出具体的错误日志，如compose logs。

**Comment by OomelodyoO** [comment]
@prontera 
Creating springcloudresttcc_solar_mysql_1 ... 
Creating springcloudresttcc_jce_java_1 ... 
Creating springcloudresttcc_rabbitmq_1 ... 
Creating springcloudresttcc_solar_mysql_1
Creating springcloudresttcc_jce_java_1
Creating springcloudresttcc_solar_mysql_1 ... error

ERROR: for springcloudresttcc_solar_mysql_1  Cannot start service solar_mysql: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/usr/share/zoneinfo/Asia/Shanghai\\\" to rootfs \\\"/var/lib/docker/overlay2/9a9b3382a81845c19b831758e51db62d7b1cace95d29f70376df2163e51721d5/merged\\\" at \\\"/usr/share/zoneinfo/Asia/Shanghai\\\" caused \\\"stat /usr/share/zoneinfo/Asia/Shanghai: input/output error\\\"\""
Creating springcloudresttcc_rabbitmq_1 ... done

ERROR: for solar_mysql  Cannot start service solar_mysql: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/usr/share/zoneinfo/Asia/Shanghai\\\" to rootfs \\\"/var/lib/docker/overlay2/9a9b3382a81845c19b831758e51db62d7b1cace95d29f70376df2163e51721d5/merged\\\" at \\\"/usr/share/zoneinfo/Asia/Shanghai\\\" caused \\\"stat /usr/share/zoneinfo/Asia/Shanghai: input/output error\\\"\""

ERROR: Encountered errors while bringing up the project.

**Comment by tanjianhui1979** [comment]
可以自己创建mysql实例（docker或非docker），然后在hosts文件中配置（IP地址根据实际情况填写）：
127.0.0.1 solar_mysql

然后用root登录执行docker-mysql/db/init_mysql_user.sql文件中的SQL语句即可

rabbitmq可以使用同样的方法处理

**Comment by prontera** [comment]
@OomelodyoO 抱歉因为之前太忙，没关注GitHub，看您的错误日志有提到路径映射，可以先关注下您的机器上是否有'/usr/share/zoneinfo/Asia/Shanghai'这个文件（当然未必是由于这个所导致的异常），或者如 @tanjianhui1979 的建议，使用自己的docker实例，如有问题欢迎继续反馈。

**Comment by Shiyajian** [comment]
我也遇到了，问题是这个zoneinfo的目录没有被共享，参考https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known；
