### ISSUE TITLE
功能很完善很强大，不过例子工程好像比较复杂，根据例子项目用于自己的项目要做的工作很多，用起来难度很大

### ISSUE THREAD

**Issue by dreamtan** [prontera/solar#33]
例子工程组：
order-ms工程：42个类
product-ms工程：25个类
account-ms工程：31个类
OrderService.java 12个方法，228行
ProductStockTccService.java 8个方法，147行
UserBalanceTccService.java 8个方法，151行
如果能做一个简化版本，例子工程如果能简化抽取部分代码放到一个已有的基础lib工程被引用就能更好的推广应用^_^

**Comment by narci2010** [comment]
赞成！

**Comment by narci2010** [comment]
希望作者有空能完善框架的使用文档！感谢。

**Comment by prontera** [comment]
本项目回归主题rest-tcc，已全部重写，并详细补充实现细则，感谢两位关注，有问题可继续交流。
