### ISSUE TITLE
config-ms工程中的git服务器域名已经更改

### ISSUE THREAD

**Issue by tanjianhui1979** [prontera/solar#40]
https://git.oschina.net/witless/conf-repo.git已经改为https://gitee.com/witless/conf-repo.git
访问https://git.oschina.net/witless/conf-repo.git会自动跳转https://gitee.com/witless/conf-repo.git
启动的时候貌似会出现问题

**Comment by prontera** [comment]
本项目回归主题rest-tcc，已全部重写，并详细补充实现细则，感谢关注，有问题可继续交流。
