### ISSUE TITLE
主事物失败

### ISSUE THREAD

**Issue by dengqiangloveju** [prontera/solar#42]
如果A服务调用B、C服务，用这种要是B、C都确认成功了，要是本地事物失败了怎么办这个好像没有考虑到吧？楼主是不是？

**Comment by prontera** [comment]
至于本地事务失败会直接向调用方抛出异常，应与上游错误重试策略，并负责应发起重试以摊分可靠性保证的责任。
本项目回归主题rest-tcc，相关模块已全部重写，精简无关组件，并详细补充tcc实现细则，感谢关注，有问题可继续交流。
