### ISSUE TITLE
能否补全文档及项目

### ISSUE THREAD

**Issue by lapDog** [prontera/solar#43]
你好，研究了你的库，受益匪浅。是否可以补全详细文档及项目其他模块，如安全模块。谢谢。

**Comment by prontera** [comment]
本项目回归主题rest-tcc，相关模块已全部重写，精简无关组件，并详细补充tcc实现细则。
首先说声抱歉，由于工作过于繁忙，疏于照料GItHub，如今才回复深感歉意，如今安全模块已经被下线，如果有安全需求，在内网中可以考虑JWT的解决方案。
