### ISSUE TITLE
必须设置重试以防参与者宕机或网络抖动

### ISSUE THREAD

**Issue by lnsoftware** [prontera/solar#46]
CoordinateService 是如何防参与者宕机或网络抖动的？

**Comment by prontera** [comment]
上游必须对甄别响应状态，针对异常情况发起重试。

另外本项目回归主题rest-tcc，相关模块已全部重写，精简无关组件，并详细补充tcc实现细则，感谢关注，有问题可re-open或继续在GitHub Issue中交流！
