### ISSUE TITLE
参与者如何实现幂等性

### ISSUE THREAD

**Issue by lnsoftware** [prontera/solar#47]
参与者是如何实现幂等性的？

**Comment by prontera** [comment]
请求内必须带有唯一标记，如orderId。Participant在收到请求先尝试从DB中恢复事务，如果没找到相关事务则视为新事务处理。

另外本项目回归主题rest-tcc，相关模块已全部重写，精简无关组件，并详细补充tcc实现细则，感谢关注，有问题可re-open或继续在GitHub Issue中交流！
