### ISSUE TITLE
请问设计图是是用什么软件画的呢？多谢

### ISSUE THREAD

**Issue by moneyice** [prontera/solar#48]

**Comment by mstao** [comment]
同问，感觉很好看

**Comment by aaronwong1989** [comment]
同问，感觉很好看

**Comment by jobschen333** [comment]
同求

**Comment by lioncui** [comment]
同求

**Comment by Kidlovec** [comment]
同问，感觉很有趣

**Comment by prontera** [comment]
前期使用OmniGraffle绘图，现在使用Draw.io，但图所需表达的正确性与严谨性应高于美观性。

另外本项目回归主题rest-tcc，相关模块已全部重写，精简无关组件，并详细补充tcc实现细则，感谢关注，有问题可re-open或继续在GitHub Issue中交流！
