### ISSUE TITLE
太重了，我只想学习下tcc，搞了一大堆东西，不能开箱即用

### ISSUE THREAD

**Issue by strivezheng** [prontera/solar#49]
一堆环境，一堆依赖，不能开箱即用。作为学习TCC的话，链路追踪、config-server、docker这些都不需要的。

**Comment by yxc135** [comment]
作者给的是tcc、限流、熔断、降级、链路追踪等等集成在一起的解决方案，但我感觉大家都是冲着tcc来的。。。。

**Comment by prontera** [comment]
本项目回归主题rest-tcc，相关模块已全部重写，精简无关组件，并详细补充tcc实现细则，感谢关注，有问题可re-open或继续在GitHub Issue中交流！
