### ISSUE TITLE
请问在下单生成预订单时是如何实现t_product_stock_tcc表添加并移除数据的

### ISSUE THREAD

**Issue by feiZzz** [prontera/solar#52]
请问在下单生成预订单时是如何实现t_product_stock_tcc表添加并移除数据的

**Comment by prontera** [comment]
本项目回归主题rest-tcc，相关模块已全部重写，精简无关组件，并详细补充tcc实现细则，感谢关注，有问题可re-open或继续在GitHub Issue中交流！
