### ISSUE TITLE
事务协调器

### ISSUE THREAD

**Issue by developerztc** [prontera/solar#54]
楼主，有个疑问，在预留资源后为什么没有把预留结果上报到事务协调器

**Comment by prontera** [comment]
因为RESTful TCC完全复用了HTTP的响应码，所以在Coordinator向Participant发起reserving操作时，可以根据Participant的响应码得知是否有操作成功。你看看这样能解决你的疑问么？

另外本项目回归主题rest-tcc，相关模块已全部重写，精简无关组件，并详细补充tcc实现细则，感谢关注，有问题可re-open或继续在GitHub Issue中交流！
