### ISSUE TITLE
您好 我想问 您这个框架结构图用什么工具画的

### ISSUE THREAD

**Issue by zhangChaoWrecked** [prontera/solar#55]

**Comment by prontera** [comment]
前期使用OmniGraffle绘图，现在使用Draw.io，但图所需表达的正确性与严谨性应高于美观性。

另外本项目回归主题rest-tcc，相关模块已全部重写，精简无关组件，并详细补充tcc实现细则，感谢关注，有问题可re-open或继续在GitHub Issue中交流！
