### ISSUE TITLE
关于数据校验与CrudMapper的疑问

### ISSUE THREAD

**Issue by Mrshengjie** [prontera/solar#6]
数据检验,HibernateValidatorAspect是用于数据校验的吗?想跟您学习一下你封装这个完整项目的思路,看你的报错啊,状态什么的都弄的很好.想了解一下...

**Comment by prontera** [comment]
@Mrshengjie 您看得很仔细，这个Aspect正是用于字段校验。

**Comment by devpage** [comment]
学习了，很好的资源

**Comment by Mrshengjie** [comment]
@prontera 我记得 controller中带的@Valid这对应的校验,是否就能满足?

**Comment by Mrshengjie** [comment]
您的项目我看也封装了超级CrudMapper,如果遇到关系表联表查询,对象可能不是单纯的数据库列对应domain里的User对象,比如会在User的基础上加上另一个对象,您怎么处理? mybatis不像hibernate,对象间的关系都是用对象,mybatis用MBG生成的都是ID.这样关系对象如何处理,问题比较弱智,见笑了.

**Comment by prontera** [comment]
CrudMapper仅是简单的辅助工具，如果需要级联查询依然是需要手工编写Mapping，按照我的习惯个人更加倾向于多个Mapper之间的数据“整合”，而不是在Mapping中编写级联查询，这样能让代码变得更为通用。

**Comment by Mrshengjie** [comment]
有相关您写的案例吗?我学习一下,我也想代码通用一点,看起来不那么杂乱,mybatis也是刚用.请多指教.....

**Comment by prontera** [comment]
@Mrshengjie 本示例就已经是一个案例，对于MyBatis的初学者建议自己练习写一两个小项目，这样才能更加有体会。

**Comment by Mrshengjie** [comment]
@prontera 我的意思是用您这种通CrudMapper,再多表联合查询的...想学习一下您说的通用点的写法.

**Comment by prontera** [comment]
@Mrshengjie 其实我这种也不算是通用Mapper，因为映射文件连该有的依然要有。当时在学习MyBatis的时候有看过一种真正可通用的，曾经叫做tkMapper，现在貌似已经改名了，[直通车在这里](http://git.oschina.net/free/Mapper)。

**Comment by Mrshengjie** [comment]
@prontera 这个我之前看过.感谢.
