### ISSUE TITLE
启动mysql容器失败

### ISSUE THREAD

**Issue by xinluke** [prontera/solar#7]
Attaching to springcloudresttcc_jce_java_1, springcloudresttcc_solar_mysql_1, springcloudresttcc_rabbitmq_1
jce_java_1     | jce java
solar_mysql_1  | Initializing database
springcloudresttcc_jce_java_1 exited with code 0
springcloudresttcc_solar_mysql_1 exited with code 1

**Comment by Mrshengjie** [comment]
自己去配置文件里把flyway.enabled改为:false,手动建一下sql,

**Comment by prontera** [comment]
@xinluke 您好，建议先系统地学习一下Docker，如启动、停止和查询日志等一系列操作。或者可以自己配置中间件，不选择Docker作为启动项，相关的启动操作均已在README中说明，再次感谢您的支持。
