### ISSUE TITLE
membership-ms没有配置Dockerfile

### ISSUE THREAD

**Issue by raydl007** [prontera/solar#8]
执行build.sh,报如下错误:
Building membership
ERROR: Cannot locate specified Dockerfile: Dockerfile

**Comment by prontera** [comment]
@raydl007 万分抱歉，当时由于时间的关系仅仅在IDE测试过后便推送到仓库，现已添加Dockerfile并修正pom文件，并在本机上成功地构建了镜像，如有发现其他错误望能继续反馈，感谢！

**Comment by raydl007** [comment]
@prontera 不敢当,要谢谢您贡献出了如此宝贵的资源
