### ISSUE TITLE
无法启动mysql,错误日志如下

### ISSUE THREAD

**Issue by raydl007** [prontera/solar#9]
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/usr/share/zoneinfo/Asia/Shanghai\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/3a6200731c361eef122ee6ef0deb4eebf0e397597a4a3ebada85d54672360a11\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/3a6200731c361eef122ee6ef0deb4eebf0e397597a4a3ebada85d54672360a11/usr/share/zoneinfo/PRC\\\" caused \\\"not a directory\\\"\""

**Comment by raydl007** [comment]
应该是"/usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai:ro"引起的,目录的映射存在问题,你是用的linux开发么

**Comment by prontera** [comment]
@raydl007 鄙人使用的是MacOS作为开发环境，可以把该volume去掉，但是要注意MySQL与宿主机器的时间问题。

**Comment by raydl007** [comment]
恩,好的,谢谢
